### ISSUE TITLE
Language switch not refreshing token

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#218]
Reproduce by going into onboarding campaigns and switch language.
It will properly reflect in onbaording itself , but console shows error
```
Unhandled rejection ReferenceError: request is not defined
    at https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:1323696
    at o (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:153744)
    at o._settlePromiseFromHandler (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:127147)
    at o._settlePromise (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:127947)
    at o._settlePromise0 (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:128646)
    at o._settlePromises (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:129973)
    at https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:83529
    at <anonymous>
From previous event:
    at o.h [as _captureStackTrace] (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:91229)
    at o._then (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:122594)
    at o.then (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:120950)
    at p.o.then (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:77913)
    at Object.n.setLocale (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:1323672)
    at String.n.onLanguageChange (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:1816207)
    at Object.r (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:360007)
    at i (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:358355)
    at Object.s [as executeDispatchesInOrder] (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:358570)
    at d (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:170552)
    at m (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:170678)
    at Array.forEach (native)
    at r (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:445319)
    at Object.processEventQueue (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:171736)
    at r (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:685551)
    at Object.handleTopLevel [as _handleTopLevel] (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:685621)
    at o (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:707434)
    at r.perform (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:240141)
    at Object.batchedUpdates (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:706983)
    at Object.o [as batchedUpdates] (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:31551)
    at dispatchEvent (https://develop.businessnetwork.opuscapita.com/onboarding/static/main.10e06a856ea86e61c452.js:1:708289)
```

Switching to bnp clearly shows it is still running in english

**Comment by kwierchris** [comment]
Fixed
