### ISSUE TITLE
ncc_onboard not working without query params

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#85]
onboarding/public/ncc_onboard
```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at app.get (/home/node/onboarding/src/server/routes/index.js:91:38)
    at Layer.handle [as handle_request] (/var/tmp/base/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/tmp/base/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/tmp/base/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/tmp/base/node_modules/express/lib/router/layer.js:95:5)
    at /var/tmp/base/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/tmp/base/node_modules/express/lib/router/index.js:335:12)
    at next (/var/tmp/base/node_modules/express/lib/router/index.js:275:10)
    at goNext (/var/tmp/base/node_modules/webpack-dev-middleware/middleware.js:28:49)
    at webpackDevMiddleware (/var/tmp/base/node_modules/webpack-dev-middleware/middleware.js:40:33)
    at Layer.handle [as handle_request] (/var/tmp/base/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/tmp/base/node_modules/express/lib/router/index.js:317:13)
    at /var/tmp/base/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/tmp/base/node_modules/express/lib/router/index.js:335:12)
    at next (/var/tmp/base/node_modules/express/lib/router/index.js:275:10)
```
need to inject proper default to bring up the page in preview mode

**Comment by gr4per** [comment]
added default query params
